name: Go CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-matrix:
    name: Test on Multiple Go Versions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [1.20, 1.21, 1.22]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            # Go mod cache
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ matrix.go }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ matrix.go }}-

      - name: Go mod tidy
        run: go mod tidy

      - name: Build
        run: go build -v ./...

      - name: Run tests
        run: go test -v ./...
